CREATE TABLE [dbo].[UserRol](
	[UserId] [nvarchar](128) NOT NULL,
	[RoleId] [nvarchar](128) NOT NULL,
 CONSTRAINT [PK_dbo.UserRol] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY], 
    CONSTRAINT [FK_UserRol_User] FOREIGN KEY (UserId) REFERENCES [dbo].[User](Id), 
    CONSTRAINT [FK_UserRol_Role] FOREIGN KEY (RoleId) REFERENCES [dbo].[Role](Id)
) ON [PRIMARY]
GO